import React, { useState } from "react";

function App() {
  const [summary, setSummary] = useState("");
  const [actions, setActions] = useState([]);
  const [loading, setLoading] = useState(false);

  const handleUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setLoading(true);
    setSummary("");
    setActions([]);

    // Simulate backend call (replace later with API call)
    setTimeout(() => {
      setSummary("This is a sample meeting summary generated by AI.");
      setActions([
        "Frontend team to finish UI by Monday",
        "Backend team to integrate APIs by end of month",
        "All members to send weekly updates",
      ]);
      setLoading(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-gray-100">
      {/* Navbar */}
      <nav className="bg-indigo-600 text-white p-4 text-xl font-bold shadow-md">
        AI Meeting Summarizer
      </nav>

      {/* Upload Section */}
      <div className="max-w-2xl mx-auto p-6">
        <h2 className="text-lg font-semibold mb-2">Upload Meeting File</h2>
        <input
          type="file"
          accept=".txt,.mp3,.wav"
          onChange={handleUpload}
          className="block w-full text-sm text-gray-700 border border-gray-300 rounded-lg cursor-pointer bg-white p-2"
        />
      </div>

      {/* Results Section */}
      <div className="max-w-3xl mx-auto p-6">
        {loading ? (
          <p className="text-center text-gray-600 animate-pulse">
            Processing your meeting... ⏳
          </p>
        ) : (
          <>
            {summary && (
              <div className="bg-white p-4 rounded-lg shadow mb-4">
                <h3 className="text-xl font-bold mb-2">Summary</h3>
                <p className="text-gray-700">{summary}</p>
              </div>
            )}

            {actions.length > 0 && (
              <div className="bg-white p-4 rounded-lg shadow">
                <h3 className="text-xl font-bold mb-2">Action Items</h3>
                <ul className="list-disc pl-6 text-gray-700">
                  {actions.map((a, i) => (
                    <li key={i}>{a}</li>
                  ))}
                </ul>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

export default App;
